### ISSUE TITLE
[BUG] Manque le mod Integrated Crafting

### ISSUE THREAD

**Issue by ravel10** [Gogo08190/chroma-sky-2#1]
### Description of the Bug

Dans l'une des quêtes d' Integrated Dynamics, il est demandé d'obtenir un avancement qui consiste à crafter un "Crafting Writer" mais je ne le trouve pas dans JEI

### Expected Behaviour

Il devrait avoir le craft du "Crafting Writer" dans JEI

### Modpack Version

1.0.2

### Screenshots

![image](https://user-images.githubusercontent.com/36196418/158440799-fe5bb6cf-c0bf-42bb-b902-07f7cc0421e8.png)

### Extra Info

Je pense qu'il faut ajouter Integrated Crafting

**Comment by Gogo08190** [comment]
En effet nous avons retiré le mod Integrated Crafting a cause d'un bug lors de la beta je vais retirer cette quête pour la prochaine mise a jour.

Merci :)
