### ISSUE TITLE
[BUG] Quest "Primary Resources" can't be completed

### ISSUE THREAD

**Issue by BigFatWizard** [Gogo08190/chroma-sky-2#10]
### Description of the Bug

The Quest "Primary Resources" (Chapter 1 - Getting Started) does not recognize the blocks needed. This makes the quest impossible to complete, permanently locking you out of unlocking Ultiminer.

### Expected Behaviour

Grab 16 of each:
Gravel Block
Dirt Block
Sand Block
Dust Block

### Modpack Version

1.0.3

### Screenshots

As seen in the screenshot, I got 16 of each Block in my hotbar, but the quest log on the right says 0/16 for each of them.
![2022-04-19_13 02 20](https://user-images.githubusercontent.com/8786791/163990389-39d418fc-ce9c-4434-8050-6f8b3ce4727a.png)
![2022-04-19_13 05 28](https://user-images.githubusercontent.com/8786791/163990406-1b477aa3-3233-4c8a-a0ee-155fdd4d75c4.png)

**Comment by koepss** [comment]
Look the dependencie

**Comment by BigFatWizard** [comment]
Literally 2 mins after writing that bug report, I realize that this quest has "8x Cobblestone" as requirement, which I haven't completed yet. This explains why the quest couldn't be completed. After doing the "8x Cobblestone" quest, "Primary Resources" was completed with it.

So this is working as intended, but I still do highly recommend to move the placement of the quests. It is not visible, that this quest is a dependency for the "Primary Resources", possibly confusing the user. Especially newcomers/first time mod users might have problems with it.

**Comment by Gogo08190** [comment]
Or look dependencies arrow.
