### ISSUE TITLE
[BUG] Muffler bugged

### ISSUE THREAD

**Issue by HToshirO** [Gogo08190/chroma-sky-2#11]
### Description of the Bug

0 muffler work

### Expected Behaviour

extrem muffler
pedestal didnt work

### Modpack Version

1.0.4

### Screenshots

![image](https://user-images.githubusercontent.com/53542616/164485020-84cc2e6d-75f3-4222-a2ba-8b3adabdcb6e.png)
![image](https://user-images.githubusercontent.com/53542616/164485206-d8eb7c14-6ccd-424d-b50a-f698d5ad72d1.png)

### Extra Info

maybe it come from immersiveFX

**Comment by Gogo08190** [comment]
Removing ImmersiveFX for the next update.
