### ISSUE TITLE
RFTools Endergenic Generator Not Displaying Information Above Block

### ISSUE THREAD

**Issue by ratkinsonuk** [Gogo08190/chroma-sky-2#12]
### Description of the Bug

I'm just setting up a simple 4-block Endergenic Generator power generation, something I've done in other packs. Holding the RFTools wrench should display real-time information above the generators about the movement of the Ender Pearls, but there's nothing showing at all.

I have Optifine installed, which I assumed was the issue, but I'm still seeing nothing after disabling it.

Without this information, it's impossible to create a full size RFTools generator farm.

### Expected Behaviour

Should display information above the generator block, as per https://youtu.be/gd5l3T4IFc0?t=532

### Modpack Version

1.0.3

### Screenshots

![image](https://user-images.githubusercontent.com/25905667/164947741-f71656b4-936b-48a8-bbce-3152a1ed594b.png)

**Comment by Gogo08190** [comment]
You can setup a full ender generator without information just right click on a generator. Report this issue on rftools.
