### ISSUE TITLE
[BUG] Beheading issue with Mob Masher

### ISSUE THREAD

**Issue by Chaos2023** [Gogo08190/chroma-sky-2#13]
### Description of the Bug

Mob grinding utils mob masher does not drop mob heads with 10 beheading upgrades. 

### Expected Behaviour

10 beheading upgrades should drop blaze heads. Have almost a double chest of rods and no heads. 

### Modpack Version

1.0.3

**Comment by Gogo08190** [comment]
Report to mob grinding utils.
