### ISSUE TITLE
[SUGGESTION] How can I get The Final Star Shard

### ISSUE THREAD

**Issue by plcyc2333** [Gogo08190/chroma-sky-2#15]
### Description of Suggestion

The Final Star Shard need 137,438,953,472 Klein Star Ein to craft. 
It is nearly impossible to craft this item directly when this modpack ban the EMC of it.
However, I do not find any other way to get this item, since it is a necessary item to craft the final creative item.

### How does this improve the experience?

If this modpack have any other ways to get this item, PLEASE offer any hints in the quest.

**Comment by Gogo08190** [comment]
Next update.
