### ISSUE TITLE
Laser port duplication bug

### ISSUE THREAD

**Issue by clavierp** [Gogo08190/chroma-sky-2#16]
When rotating a laser port from mini utilities with a crescent hammer, a copy of the laser is dropped. You can dupe laser port. Not sure if it is useful though.

**Comment by Gogo08190** [comment]
I don't have this dup with the latest version of chroma sky 2

**Comment by dju** [comment]
Same duplicating bug with wrench from supplementaries (shift right click on laser port)
Chroma Sky 2 - 1.0.5
