### ISSUE TITLE
[SUGGESTION] *Replace with brief description of suggestion*

### ISSUE THREAD

**Issue by mythpan1** [Gogo08190/chroma-sky-2#18]
### Description of Suggestion

Is that have some improve at FPS, I can got 180 FPS on chroma tech 2, but the chroma sky 2 only 30 FPS.  I mention the chroma tech 2 use the isrs, but the chroma sky 2 not use. is that can add the isrs on chroma sky 2? I try to manually install, but not work! 

### How does this improve the experience?

I think should improve the play feeling

### Screenshots

![2022-05-27 (2)](https://user-images.githubusercontent.com/43778494/170627305-4b1d11ab-e2ca-49ee-a481-c903de717b8a.png)

![2022-05-27 (1)](https://user-images.githubusercontent.com/43778494/170625578-69b2289c-dbcb-42ce-af2e-f50089b9f3e8.png)

**Comment by Gogo08190** [comment]
Add magnesium mod

**Comment by mythpan1** [comment]
> Add magnesium mod

thanks! after add magnesium mod, I got huge improve, the FPS 800 now.
