### ISSUE TITLE
[SUGGESTION] add tags for vanilla ores in ID's mechanical squeezer

### ISSUE THREAD

**Issue by Overseer9** [Gogo08190/chroma-sky-2#21]
### Description of Suggestion

Default ID's mechanical saueezer didn't have any tags for processing vanilla ores, so it would be great to add the tags so clusters like iron, gold, diamond can be processed with mechanical squeezer

### How does this improve the experience?

It helps early game players that didn't have any access to IE's crusher yet to be able to process clusters without using any FTB jar

**Comment by Gogo08190** [comment]
JAR are used to process cluster only. You can use tinker for ore.
