### ISSUE TITLE
lack of icons and texture to blocks of Masterful machinery mod

### ISSUE THREAD

**Issue by Canbinlol** [Gogo08190/chroma-sky-2#3]
### Description of the Bug

icons in jei:
![@XZ6D~SDEF4NAVVEY@2JQI7](https://user-images.githubusercontent.com/91358346/159458401-c63f2178-8fd7-499d-a675-509b59a05eb0.png)

block textures in multiblock structure preview:
![6HV G214J VB7`TA C`29P6](https://user-images.githubusercontent.com/91358346/159458476-ac473c7d-978f-49bf-8397-74b54e64d86c.png)

icons in the mission page:
![K}HS~WISDIUYKDAMBWSZ~XI](https://user-images.githubusercontent.com/91358346/159458542-7b7f84b8-4950-4833-b468-aa7c9fcab29a.png)

Though i have seen "mm memory pack" in resourcepacks, it seems not working exactly for me.

### Expected Behaviour

have some accustomed icon and block texture.

### Modpack Version

both 1.0.1 and 1.0.2

### Extra Info

extra mods added:
i18nupdatemod-1.16.5-2.0.2-hotfix-4
JustEnoughCharacters-1.16.4-4.1.5
lootbeams-1.16.5-release-sept0621
Xaeros_Minimap_22.3.0_Forge_1.16.5
XaerosWorldMap_1.20.3.1_Forge_1.16.5

**Comment by Gogo08190** [comment]
Can't fix that because you added mods. 
No problems on our side.

**Comment by Canbinlol** [comment]
yeah it worked after i reinstalled the modpack, thanks anyway.

**Comment by Canbinlol** [comment]
> Can't fix that because you added mods. No problems on our side.

just a reminder in case u faced with similar problem, the problem was caused by i18n mod and i have reported issue to them. Thanks.
