### ISSUE TITLE
[BUG] Chroma Sky 2 kube js error

### ISSUE THREAD

**Issue by Gragonlse** [Gogo08190/chroma-sky-2#30]
### Description of the Bug

reloaded with no kubejs errors 

### Expected Behaviour

Start up w/o error

### Modpack Version

Chroma Sky 2 1.0.7

### Screenshots

![image](https://user-images.githubusercontent.com/114092056/191548400-3233a07e-cd95-4653-85ec-bc20c897fd91.png)

**Comment by Gogo08190** [comment]
What is the bug ?

**Comment by Gragonlse** [comment]
there are several features of the mod pack that does not work

**Comment by Gogo08190** [comment]
No problems with the modpack

**Comment by Gragonlse** [comment]
okay I didn't know

**Comment by Gragonlse** [comment]
do you know how to solve it ?

**Comment by Gogo08190** [comment]
Solve what ?

**Comment by Gogo08190** [comment]
Stupid.
