### ISSUE TITLE
[SUGGESTION] Add a possibility to autocraft resonating gem in starlight infuser

### ISSUE THREAD

**Issue by Armixi** [Gogo08190/chroma-sky-2#4]
### Description of Suggestion

A Masterful Machinery structure for the starlight infuser would be a nice addition to an already great pack. I know there is probably a way to automate it with Integrated Dynamics, but honestly it's a bit of a pain when you are not used to logic programming, and from what I found, there is still a possibility that it won't even work correctly.

### How does this improve the experience?

It would be especially useful for the end game part, since resonating gem is used for the ultimate gem, which is used for a lot of creative item. You could still do it manually, but I dont know anybody who love manual and repetitive labour while you have automation for everything else.

**Comment by Gogo08190** [comment]
It's a good Idea ! 

I'll add this in the next update 😀
