### ISSUE TITLE
Game lags shortly when fluid world importer works

### ISSUE THREAD

**Issue by raphael-klbm** [Gogo08190/chroma-sky-2#6]
When the fluid world importer from Integrated Dynamics pulls one bucket of water from an infinite water source, the game freezes shortly. When I pick up a bucket of water from an infinite water source, the game does not freeze.
The modpack version is 1.0.3. The game did not freeze in version 1.0.2.

**Comment by Gogo08190** [comment]
Report this problem here : https://github.com/CyclopsMC/IntegratedDynamics/issues
