### ISSUE TITLE
[BUG] kubejs startup error

### ISSUE THREAD

**Issue by toruPuchuu** [Gogo08190/chroma-sky-2#7]
### Description of the Bug

From logs\kubejs\startup.txt:
[ERR  ] Error occurred while handling event 'item.modification': ReferenceError: "cyclicTools" is not defined. (startup_scripts:vanillatools.js#79)

### Expected Behaviour

Start up w/o error

### Modpack Version

Chroma Sky 2 - 1.0.3

### Extra Info

Windows 10

**Comment by Gogo08190** [comment]
Your server or your modpack is incorrectly installed.

**Comment by toruPuchuu** [comment]
- Copied instance folder and deleted it.
- Installed Chroma Sky 2 - 1.0.3 using GDLauncher v 1.1.22-beta.1
- Created a new world.
- Same kubejs error.

In kubejs\startup_scripts\vanillatools.js, cyclicbTools is defined at the top, but cyclicTools (no b) is used down below. Typo

**Comment by Gogo08190** [comment]
Problem with gdlauncher use curseforge overwolf.

**Comment by toruPuchuu** [comment]
Installed with Curseforge/Overwolf and have the same issue; cf/ow just doesn't report it in chat. There is a typo in kubejs\startup_scripts\vanillatools.js: In lie 6 cyclic**b**Tools is defined, but in line 79 it is used as cyclicTools (no b).

From latest.log
[Worker-Main7/ERROR]: Error occurred while handling event 'item.modification': ReferenceError: "cyclicTools" is not defined. (startup_scripts:vanillatools.js#79)

Again, this is a fresh install using Curseforge/Overwolf with no changes or additions. Please fix your typo.
