### ISSUE TITLE
[SUGGESTION] Can I use this mod package to send a personally made video?

### ISSUE THREAD

**Issue by MRailgun** [Gogo08190/chroma-sky-2#8]
### Description of Suggestion

If I want to record a video with a Chrome Sky2 module package and send it to a website like Bilibili, do I need to get authorization? What do I need to pay attention to.

### How does this improve the experience?

If I want to record a video with a Chrome Sky2 module package and send it to a website like Bilibili, do I need to get authorization? What do I need to pay attention to.

**Comment by Gogo08190** [comment]
You can make chroma sky 2 video
