### ISSUE TITLE
The recipe of Enderium Ingot is vanished

### ISSUE THREAD

**Issue by plcyc2333** [Gogo08190/chroma-sky-2#9]
In version 1.0.3, I find that the recipe of Enderium Ingot and the dust are vanished.
Then roll back to version 1.0.2, the recipe is normal. 
I do not see the changelog about this.
Is this a bug, or planned?

**Comment by koepss** [comment]
hello, for the moment you can use the tinker's craft.

**Comment by koepss** [comment]
Fix in next update
